name: learn-github-actions
on: [deployment]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: Mudlet/xmlstarlet-action@v1.1
        with:
          args: ed -r "//*/@id" -v ID xml/tab-obj.xml
